repos:
  - repo: https://github.com/ambv/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.2.0'
    hooks:
      - id: mypy
  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.19.1
    hooks:
      - id: gitlint
        args:
          - '--ignore=body-is-missing,T3,CC1'
          - '--contrib=CT1'
          - '-cCT1.types=feat,chore,fix,wip,refactor,docs,test,dev,perf'
          - '-ctitle-max-length.line-length=120'
          - '--msg-filename'
